[package]
name = "openfrag-live"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
openfrag-capture = { path = "../openfrag-capture" }
openfrag-domain = { path = "../openfrag-domain" }
openfrag-gsi = { path = "../openfrag-gsi" }

[lints]
workspace = true
